### ISSUE TITLE
[0.1.4] No actions found in Plugin version.

### ISSUE THREAD

**Issue by carlosmuvi** [fastlane-community/fastlane-plugin-firebase_app_distribution#15] opened 2019-10-11 16:53 UTC
Hi! Looks like when installing plugins, no actions are found in the latest version (0.1.4 at the time of writing) of `firebase_app_distribution`.

Fixing version to `0.1.2`:

![image](https://user-images.githubusercontent.com/625017/66669554-b41ece00-ec4f-11e9-8e05-8d925d6b13b8.png)

With version `0.1.4`:

![image](https://user-images.githubusercontent.com/625017/66669693-f0eac500-ec4f-11e9-9f65-04930b225ef3.png)

**Comment by rebehe** [comment] 2019-10-11 17:04
Hi Carlos! Engineer on App Distribution - sorry to hear that. We'll look into it and get back to you soon!

**Comment by rebehe** [comment] 2019-10-11 20:26
@carlosmuvi what version of Ruby are you using? (you can run `fastlane env` to check)

**Comment by artem-zaitsev** [comment] 2019-10-14 11:48
I have same error. And have this log%
Error loading plugin 'fastlane-plugin-firebase_app_distribution': cannot load such file -- fastlane/plugin/firebase_app_distribution

**Comment by artem-zaitsev** [comment] 2019-10-14 12:27
@carlosmuvi @rebehe I have solution: upgade ruby to 2.5.5 (i had 2.3).

**Comment by TheDancerCodes** [comment] 2019-10-14 13:02
> @carlosmuvi @rebehe I have solution: upgrade ruby to 2.5.5 (i had 2.3).

Hi @artem-zaitsev 
This didn't work for me sadly. Facing the same issue.

<img width="1440" alt="Screenshot 2019-10-14 at 16 01 09" src="https://user-images.githubusercontent.com/6739804/66753168-ddcc3500-ee9b-11e9-93cb-1d5085e99ccb.png">

**Comment by TheDancerCodes** [comment] 2019-10-14 14:18
> @carlosmuvi @rebehe I have solution: upgrade ruby to 2.5.5 (i had 2.3).

This worked for me as well(Upgrade ruby to 2.5.5). Thanks @artem-zaitsev 👏

**Comment by TheDancerCodes** [comment] 2019-10-14 14:19
> @carlosmuvi what version of Ruby are you using? (you can run `fastlane env` to check)

Hello @rebehe 
Version `2.3` of Ruby is what results in this issue. Upgrading to `2.5.5` sorts it out.

**Comment by khadorkin** [comment] 2019-10-14 19:48
Hi @rebehe 
I have Ruby version `2.6.3`, but it is affected to me too.
Full list of `env`
```
| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15                                                          |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.21.0 (Apple Git-122)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15 (19A583)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.0                                                           |
```

**Comment by Dzamir** [comment] 2019-10-14 20:20
I also have Ruby 2.6.3 and I have the same issue

**Comment by rebehe** [comment] 2019-10-15 13:49
Hi all, thanks for the feedback! I was able to reproduce this, but upgrading Ruby to 2.4+ fixed it for me. I'll try using Ruby 2.6.3 and get back to you.

**Comment by Dzamir** [comment] 2019-10-15 15:06
I resolved the problem by installing rbenv and installing Ruby 2.5.5.

**Comment by joshdholtz** [comment] 2019-10-16 14:55
Heyyyy 👋 Few questions for you all.

1) Is this issue only with system Ruby? Or is this also being experienced with `rbenv`, `chruby`, and `rvm`?
2) Is this happening when running `bundle exec fastlane <lane>` and just `fastlane <lane>`?
3) Do other plugins work for you all? If you don't have any other plugins, can you try running `fastlane add_plugin ascii_art` to see if that one loads?

**Comment by snowtema** [comment] 2019-10-18 15:54
I have the same problem. 

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15                                                          |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.21.0 (Apple Git-122)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15 (19A583)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.1                                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ru_RU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

import "MatchLane"

# load variables from .env file in the root if it exists
if File.exist?('../.env')
  open('../.env', 'r').readlines.each do |l|
    kv = l.split('=')
    ENV[kv[0]] = kv[1].chomp
  end
end

# We have to do it ourselves because fastlane simply looks at .plist
def get_passenger_project_version
    fastlane_require 'Xcodeproj'

    project_name = '../passenger/Wheely/Wheely.xcodeproj'
    target_name = ENV["PROJECT_NAME"]
    configuration_name = 'Release'

    # Read values from the configuration,
    # specified in project settings for a specific target.
    project = Xcodeproj::Project.open(project_name)
    target = project.native_targets.find {|s| s.name == target_name }
    configuration = target.build_configurations.find {|s| s.name == configuration_name}
    return configuration.resolve_build_setting('MARKETING_VERSION')
end

# Do it ourselves because builtin tools use .plist from project
def get_passenger_build_number(destination)
	return FastlaneCore::IpaFileAnalyser.fetch_app_build('build-out/' + destination + "/#{ENV["PROJECT_NAME"]}.ipa")
end

def get_driver_project_version
	fastlane_require 'Xcodeproj'

	project_name = '../driver/WheelyDriver/WheelyDriver.xcodeproj'
	target_name = 'WheelyDriver'
	configuration_name = 'Release'

	# Read values from the configuration,
	# specified in project settings for a specific target.
	project = Xcodeproj::Project.open(project_name)
	target = project.native_targets.find {|s| s.name == target_name }
	configuration = target.build_configurations.find {|s| s.name == configuration_name}
	return configuration.resolve_build_setting('CURRENT_PROJECT_VERSION')
end

def get_driver_build_number
	return FastlaneCore::IpaFileAnalyser.fetch_app_build('build-out/Wheely Driver.ipa')
end

default_platform(:ios)

platform :ios do

	before_all do
		sh("../scripts/prepare_env.sh")
		cocoapods(
			repo_update: true,
			podfile: "passenger/Wheely/Podfile"
		)
	end

	desc "Unit-Testing passenger's app"
	lane :test do
		scan(
			workspace: "passenger/Wheely/Wheely.xcworkspace",
			scheme: "All in WheelyUnitTests"
		)
    clear_derived_data
	end

	desc "UI Testing passenger's app"
	lane :uitest do
		scan(
			workspace: "passenger/Wheely/Wheely.xcworkspace",
			scheme: "All in WheelyUITests"
			)
      clear_derived_data
	end

	lane :passenger_testflight do
		# Check that we're on release branch
		ensure_git_branch(
			branch: 'release/passenger/.+'
		)

    update_distribution_profiles()
		destination = 'TestFlight'
    ipaPath = "fastlane/build-out/#{destination}"

		# Check that branch name match application version
		branch_version = git_branch.split('/').last
		project_version = get_passenger_project_version

		if branch_version != project_version
			UI.user_error!("Project version and branch version doesn't match: '#{project_version}' vs '#{branch_version}'")
		else
			UI.success("Branch name and project version match")
		end

		# Build app
    gym(
      workspace: "passenger/Wheely/#{ENV["PROJECT_NAME"]}.xcworkspace",
      scheme: ENV["SCHEME_NAME"],
      configuration: "Release",
      skip_profile_detection: true,
      export_method: "app-store",
      export_options: {
        uploadSymbols: true,
        compileBitcode: true,
        signingStyle: "manual",
        provisioningProfiles: {
          ENV["DISTRIBUTION_BUNDLE_ID"] => ENV["DISTRIBUTION_PROVISION_PROFILE_NAME"],
          ENV["DISTRIBUTION_NOTIFICATION_SERVICE_EXTENSION_BUNDLE_ID"] => ENV["DISTRIBUTION_NOTIFICATION_SERVICE_EXTENSION_PROVISION_PROFILE_NAME"]
        },
        method: "app-store"
      },
      clean:true,
      output_directory: ipaPath,
      codesigning_identity: ENV["DISTRIBUTION_CODESIGNING_IDENTITY"]
    )

    ipa = ipaPath + "/#{ENV["PROJECT_NAME"]}.ipa"
    testflight(
      username: ENV["FASTLANE_USER"],
      ipa: ipa,
      apple_id: ENV["APPSTORE_APP_ID"],
      skip_submission: true,
      skip_waiting_for_build_processing: true
    )

		tag = "passenger/testflight/v#{project_version}_#{get_passenger_build_number(destination)}".downcase.tr(" ", "_")
		UI.message("Tagging head with #{tag}")
		add_git_tag(
 			tag: tag
		)

		push_git_tags
    clear_derived_data
	end

	lane :deploy_to_appcenter do |options|
    update_development_profiles()
    log = options[:changelog] || 'No release notes'
		destination = 'AppCenter'

		# Check that branch name match application version
		branch_version = git_branch.split('/').last
		project_version = get_passenger_project_version

		if branch_version != project_version
			UI.message("Project version and branch version doesn't match: '#{project_version}' vs '#{branch_version}'")
		else
			UI.success("Branch name and project version match")
		end

		# Build app
    ipaPath = "fastlane/build-out/#{destination}"

    gym(
      workspace: "passenger/Wheely/#{ENV["PROJECT_NAME"]}.xcworkspace",
      scheme: ENV["SCHEME_NAME"],
      configuration: "Debug",
      skip_profile_detection: true,
      export_method: "development",
      export_options: {
        uploadSymbols: true,
        compileBitcode: false,
        signingStyle: "manual",
        provisioningProfiles: {
          ENV["DEV_BUNDLE_ID"] => ENV["DEV_PROVISION_PROFILE_NAME"],
          ENV["DEV_NOTIFICATION_SERVICE_EXTENSION_BUNDLE_ID"] => ENV["DEV_NOTIFICATION_SERVICE_EXTENSION_PROVISION_PROFILE_NAME"]
        },
        method: "development"
      },
      clean:true,
      output_directory: ipaPath,
      codesigning_identity: ENV["DEV_CODESIGNING_IDENTITY"]
    )


    ipa = ipaPath + "/#{ENV["PROJECT_NAME"]}.ipa"

    appcenter_upload(
      api_token: ENV["APPCENTER_API_TOKEN"],
      owner_name: ENV["APPCENTER_OWNER_NAME"],
      app_name: ENV["APPCENTER_APP_NAME_QA"],
      ipa: ipa,
      release_notes: log,
      notify_testers: false
    )

		tag = "passenger/appcenter/v#{project_version}_#{get_passenger_build_number(destination)}".downcase.tr(" ", "_")

		UI.message("Tagging head with #{tag}")
		add_git_tag(
 			tag: tag
		)
		push_git_tags

    info  = Actions.lane_context[Actions::SharedValues::APPCENTER_BUILD_INFORMATION]
    slack(
    	message: "*Passenger* app successfuly deployed to AppCenter :rocket:",
    	success: true,
    	attachment_properties: {
           fields: [
               {
                   title: "Version",
                   value: info['short_version'] + ' (' + info['version'] + ')',
               },
               {
                   title: "Link to install",
                   value: "https://install.appcenter.ms/orgs/Wheely/apps/#{ENV["APPCENTER_APP_NAME_QA"]}",
                   short: true
               },
               {
               		title: "Release notes",
               		value: info['release_notes'],
               		short: true
               }
           ]
       })
    clear_derived_data
	end

	lane :driver_testflight do
		# Check that we're on release branch
		ensure_git_branch(
			branch: 'release/driver/.+'
		)

		# Check that branch name match application version
		branch_version = git_branch.split('/').last
		project_version = get_driver_project_version

		if branch_version != project_version
			UI.user_error!("Project version and branch version doesn't match: '#{project_version}' vs '#{branch_version}'")
		else
			UI.success("Branch name and project version match")
		end

		# Build app
		build_ios_app(
			workspace: 'driver/WheelyDriver.xcworkspace',
			scheme: 'App Store',
			configuration: 'Release',
			clean: true,
			output_directory: 'fastlane/build-out'
		)

		# Upload only, because we have to update localized 'What's new' by hand
		# https://github.com/fastlane/fastlane/issues/11421
		upload_to_testflight(
			app_identifier: 'com.wheely.partner',
			ipa: 'fastlane/build-out/Wheely Driver.ipa',
			skip_submission: true,
			skip_waiting_for_build_processing: true
		)

		tag = "driver/v#{project_version}(#{get_driver_build_number})"
		UI.message("Tagging head with #{tag}")
		add_git_tag(
 			tag: tag
		)

		UI.header("Don't forget to push tags once you're done with 'git push --tags'")
    clear_derived_data
	end

	lane :passenger_firebase do
		# Build app
		build_ios_app(
			workspace: 'driver/WheelyDriver.xcworkspace',
			scheme: 'App Store',
			configuration: 'Release',
			clean: true,
			output_directory: 'fastlane/build-out'
		)

		firebase_app_distribution(
              app: ENV['FIREBASE_APP_ID'],
              testers: "artyom.slizhik@wheely.com",
              release_notes: "Lots of amazing new features to test out!",
              firebase_cli_path: "/usr/bin/firebase"
        )
        clear_derived_data
	end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# This file is ignored in git
# In case you don't have such file, create it
# Example contents are:
# apple_id "felix@krausefx.com"
eval File.read('./Identity.rb')
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.134.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                    | Version   | Update-Status  |
| ----------------------------------------- | --------- | -------------- |
| fastlane-plugin-appcenter                 | 1.5.0     | ✅ Up-To-Date   |
| fastlane-plugin-versioning                | 0.3.4     | ✅ Up-To-Date   |
| fastlane-plugin-firebase_app_distribution | undefined | 💥 Check failed |


<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| bundler                                   | 2.0.2        |
| CFPropertyList                            | 3.0.1        |
| concurrent-ruby                           | 1.1.5        |
| i18n                                      | 0.9.5        |
| minitest                                  | 5.12.2       |
| thread_safe                               | 0.3.6        |
| tzinfo                                    | 1.2.5        |
| activesupport                             | 4.2.11.1     |
| public_suffix                             | 2.0.5        |
| addressable                               | 2.7.0        |
| httpclient                                | 2.8.3        |
| json                                      | 2.2.0        |
| algoliasearch                             | 1.27.1       |
| atomos                                    | 0.1.3        |
| babosa                                    | 1.0.3        |
| claide                                    | 1.0.3        |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| cocoapods-core                            | 1.8.4        |
| cocoapods-deintegrate                     | 1.0.4        |
| cocoapods-downloader                      | 1.2.2        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.0        |
| cocoapods-stats                           | 1.1.0        |
| netrc                                     | 0.11.0       |
| cocoapods-trunk                           | 1.4.1        |
| cocoapods-try                             | 1.1.0        |
| colored2                                  | 3.1.2        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| gh_inspector                              | 1.1.3        |
| molinillo                                 | 0.6.6        |
| ruby-macho                                | 1.4.0        |
| nanaimo                                   | 0.2.6        |
| xcodeproj                                 | 1.13.0       |
| cocoapods                                 | 1.8.4        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.10       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.4.1        |
| unf_ext                                   | 0.0.7.6      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.5        |
| emoji_regex                               | 1.0.1        |
| excon                                     | 0.67.0       |
| multipart-post                            | 2.0.0        |
| faraday                                   | 0.17.0       |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.6        |
| faraday_middleware                        | 0.13.1       |
| fastimage                                 | 2.1.7        |
| jwt                                       | 2.1.0        |
| memoist                                   | 0.16.0       |
| multi_json                                | 1.14.1       |
| os                                        | 1.0.1        |
| signet                                    | 0.12.0       |
| googleauth                                | 0.6.7        |
| mime-types-data                           | 3.2019.1009  |
| mime-types                                | 3.3          |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.23.9       |
| google-cloud-env                          | 1.2.1        |
| google-cloud-core                         | 1.3.2        |
| google-cloud-storage                      | 1.16.0       |
| mini_magick                               | 4.9.5        |
| multi_xml                                 | 0.6.0        |
| plist                                     | 3.5.0        |
| rubyzip                                   | 1.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.6        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.6.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.7.0        |
| tty-cursor                                | 0.7.0        |
| tty-spinner                               | 0.9.1        |
| word_wrap                                 | 1.0.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.0        |
| fastlane-plugin-appcenter                 | 1.5.0        |
| fastlane-plugin-firebase_app_distribution | 0.1.4        |
| fastlane-plugin-versioning                | 0.3.4        |
</details>


*generated on:* **2019-10-18**
</details>

**Comment by alexsinger** [comment] 2019-10-18 16:28
@snowtema thanks for the report! Can you answer @joshdholtz 's questions in https://github.com/fastlane-community/fastlane-plugin-firebase_app_distribution/issues/15#issuecomment-542742193 to help debug?

**Comment by snowtema** [comment] 2019-10-18 16:43
@alexsinger Yes, I can. 
1) I use `rbenv` of different Ruby versions: 2.5.5, 2.6.3
2) This is happening on both options.
3) Yes, other plugins work fine

**Comment by khadorkin** [comment] 2019-10-18 17:42
@joshdholtz 

1. I use system Ruby only
2. It is happening on both platform
3. It works as expected

**Comment by musa-almatri** [comment] 2019-10-21 09:02
Same issue

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15                                                          |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0 (Apple Git-122)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15 (19A583)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.1                                                           |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.134.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                    | Version   | Update-Status  |
| ----------------------------------------- | --------- | -------------- |
| fastlane-plugin-badge                     | 1.3.0     | ✅ Up-To-Date   |
| fastlane-plugin-firebase_app_distribution | undefined | 💥 Check failed |


<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| slack-notifier                            | 2.3.2        |
| atomos                                    | 0.1.3        |
| claide                                    | 1.0.3        |
| colored2                                  | 3.1.2        |
| nanaimo                                   | 0.2.6        |
| xcodeproj                                 | 1.12.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.6.0        |
| terminal-table                            | 1.8.0        |
| plist                                     | 3.5.0        |
| public_suffix                             | 2.0.5        |
| addressable                               | 2.7.0        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| tty-screen                                | 0.7.0        |
| tty-cursor                                | 0.7.0        |
| tty-spinner                               | 0.9.1        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| unf_ext                                   | 0.0.7.6      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.6        |
| faraday                                   | 0.17.0       |
| faraday_middleware                        | 0.13.1       |
| gh_inspector                              | 1.1.3        |
| mini_magick                               | 4.9.5        |
| multi_xml                                 | 0.6.0        |
| rubyzip                                   | 1.3.0        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 1.0.0        |
| dotenv                                    | 2.7.5        |
| bundler                                   | 2.0.2        |
| jwt                                       | 2.1.0        |
| uber                                      | 0.1.0        |
| declarative                               | 0.0.10       |
| declarative-option                        | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| mime-types                                | 3.3          |
| memoist                                   | 0.16.0       |
| os                                        | 1.0.1        |
| googleauth                                | 0.6.7        |
| httpclient                                | 2.8.3        |
| google-api-client                         | 0.23.9       |
| digest-crc                                | 0.4.1        |
| google-cloud-storage                      | 1.16.0       |
| emoji_regex                               | 1.0.1        |
| CFPropertyList                            | 3.0.1        |
| babosa                                    | 1.0.3        |
| excon                                     | 0.67.0       |
| fastimage                                 | 2.1.7        |
| json                                      | 2.2.0        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.6        |
| mime-types-data                           | 3.2019.1009  |
| multi_json                                | 1.14.1       |
| signet                                    | 0.12.0       |
| google-cloud-env                          | 1.2.1        |
| google-cloud-core                         | 1.3.2        |
| forwardable                               | 1.2.0        |
| logger                                    | 1.3.0        |
| stringio                                  | 0.0.2        |
| ipaddr                                    | 1.2.2        |
| openssl                                   | 2.1.2        |
| ostruct                                   | 0.1.0        |
| strscan                                   | 1.0.0        |
| date                                      | 2.0.0        |
| fileutils                                 | 1.1.0        |
| etc                                       | 1.0.1        |
| io-console                                | 0.4.7        |
| zlib                                      | 1.0.0        |
| libxml-ruby                               | 3.1.0        |
| rexml                                     | 3.1.9        |
| psych                                     | 3.1.0        |
| mutex_m                                   | 0.1.0        |
| curb                                      | 0.9.10       |
| badge                                     | 0.11.0       |
| fastlane-plugin-badge                     | 1.3.0        |
| fastlane-plugin-firebase_app_distribution | 0.1.4        |
</details>


*generated on:* **2019-10-21**
</details>

**Comment by joshdholtz** [comment] 2019-10-21 14:26
Hello, everybody! I think I'm starting to get somewhere here. It seems like this is almost 100% an issue with Catalina and not having enough file permissions for your terminal.

I was **not able** to replicate with Mojave on my MacBook at all 🤔 

I then upgraded Mac mini to Catalina to see if I could replicate. The only way I was able to replicate was by installing _fastlane_ on **system** Ruby and by running `sudo bundle install` (which is not recommended by `bundler` due to permission issues). 

---

❓ For everybody having issues, with system Ruby, did you happen to run `sudo bundle install`? 

💡 I think the solution you may want to try is instead by running `bundle install --path vendor/bundle`. This will install the gems relative to your project so that you won't run into system permission issues.

If somebody could try with this that would be 💯 🙏

**Comment by ShortSound** [comment] 2019-10-21 14:51
```bundle install --path vendor/bundle``` seems to be working.
Thank you!

**Comment by renanstig** [comment] 2019-10-21 14:59
I've been facing some weird issue which prevents me from installing the plugin. 
For some reason fastlane still tries to use version `2.3`, even though it doesn't exist anymore as I updated to the version 2.6. Any idea how to solve it? 
```/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: bad interpreter: No such file or directory```

**Comment by rebehe** [comment] 2019-10-22 15:50
@renanstig - it's hard to say what's causing the issue without a full stacktrace, but the path looks like it's system Ruby for Mojave. Ruby 2.6 is the default on Catalina, so maybe the Ruby path got switched. I would also recommend using `rbenv` so you don't have to deal with system Ruby.

**Comment by renanstig** [comment] 2019-10-22 15:52
@rebehe , thanks your answer. I do appreciate that. 
I could fix the issue by totally removing the fastlane from my Macbook, reinstalling it and from now on I run it using `bundle exec fastlane`. Even the plugin installed successfully after doing so.

**Comment by rebehe** [comment] 2019-10-22 15:53
Hi peeps, thanks for all the feedback! Closing this issue, please reference Josh's workaround in https://github.com/fastlane-community/fastlane-plugin-firebase_app_distribution/issues/15#issuecomment-544539746 if you're still hitting this.

Feel free to reach out if you have any more questions!

**Closed by rebehe** 2019-10-22 15:53 UTC

**Comment by joshdholtz** [comment] 2019-10-22 16:16
Going on top of everything here, I'm working on a PR for https://github.com/fastlane/fastlane that will make give a helpful error message if/when this happens again 😊

**Comment by idelfonsog2** [comment] 2019-12-06 18:42
its the path relative to the project? should it the directories be commit to source controll? @ShortSound

**Comment by soryncrash13** [comment] 2020-01-15 17:54
> `bundle install --path vendor/bundle` seems to be working.
> Thank you!

This is what fixed it for me. Running macos catalina, with the latest updates as of 15th of Jan 2020. TY :D

**Comment by pschuette22** [comment] 2020-01-21 16:26
Fix for me was to just run `sudo fastlane install_plugins` . Running without sudo gave me the error. Everything seems to be going swimmingly now. 

https://github.com/fastlane/fastlane/issues/15506

**Comment by badredaha** [comment] 2020-02-18 18:24
Try : bundle exec fastlane update_plugins

**Comment by tuktasatu** [comment] 2020-03-19 11:32
This worked for me. Try edit permission for firebase_app_distribution folder. 
https://github.com/fastlane/fastlane/issues/15506#issuecomment-566051001

**Comment by a8001271991** [comment] 2020-03-24 05:55
> This worked for me. Try edit permission for firebase_app_distribution folder.
> `sudo chmod -R a+r /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.1.4`

Thanks, it worked!

**Comment by teerayuthton** [comment] 2020-03-25 02:05
> `bundle install --path vendor/bundle` seems to be working.
> Thank you!

Works for me too
Thank you!

**Comment by shinriyo** [comment] 2020-05-05 06:58
```
ruby --version                                                                                                                      Tue May  5 06:57:30 2020
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
```

**Comment by shinriyo** [comment] 2020-05-05 08:22
0.1.3

**Comment by soryncrash13** [comment] 2020-05-05 10:23
So for me what seemed to make it work is my colleague and friend installed the gems in the same dir with the project. When i type ls in the terminal inside the project dir i have these files/dirs:
Crashlytics.framework	Podfile.lock		builds
Fabric.framework	Pods			fastlane
Gemfile			<PROJECT_NAME>			vendor
Gemfile.lock		<PROJECT_NAME>.xcodeproj
Podfile			<PROJECT_NAME>.xcworkspace

So inside vendor i have the following: bundle > ruby > 2.6.0 > bin, build_info, cache, doc, extensions, gems, specifications.

Even though before i was installing and updating the gems on my macbook (macos catalina) i didn't get to install these files in the project dir so every time i was running fastlane build and create ipa and upload to firebase distribution it got an error saying the firebase plugin is not there/not configured/installed... Now i can do everything that i want and need to.

Please try this approach and i'm pretty sure it will work, since i've also tried a lot of fixes and tips from everywhere but this worked out for me. Also i've freshly installed macos catalina and xcode on my macbook at the time of my first comment, but even now i only have a few apps/programs and i've only installed a few things in the terminal so i haven't installed anything for my macos to work. So even now it's pretty clean (apps i have installed myself: chrome, skype, sourcetree, illustrator, sketch, filezilla, steam, vs code and through the terminal i've only installed brew, cocoapods, fastlane, firebase plugin, installed and updated ruby and i think now i also have python; this is everything i have).

Sorry for the long comment :D

**Comment by deepshah7** [comment] 2020-05-14 08:53
> This worked for me. Try edit permission for firebase_app_distribution folder.
> `sudo chmod -R a+r /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.1.4`
> [fastlane/fastlane#15506 (comment)](https://github.com/fastlane/fastlane/issues/15506#issuecomment-566051001)

This one did it for me. Spent 8 hrs banging my head against the wall. Thanks!

**Comment by komorian** [comment] 2020-05-20 13:37
Looks like some kind of file permission issue under Catalina, so `chmod` might help.
But you can also install `fastlane-plugin-firebase_app_distribution` in gem's `USER INSTALLATION DIRECTORY` (`gem env` will tell you where it is).

So, I uninstalled the gem from the default dir. 
`sudo gem uninstall fastlane-plugin-firebase_app_distribution`
and then installed in user dir
`gem install fastlane-plugin-firebase_app_distribution --user-install`

and now it works.

**Comment by balakzde** [comment] 2020-06-03 13:09
In case anyone is dealing with this. I upgraded ruby to 2.7 and this problem occured. When I unsinstalled it and installed 2.6 it was resolved.

**Comment by DaivePan** [comment] 2020-09-10 01:09
> Looks like some kind of file permission issue under Catalina, so `chmod` might help.
> But you can also install `fastlane-plugin-firebase_app_distribution` in gem's `USER INSTALLATION DIRECTORY` (`gem env` will tell you where it is).
> 
> So, I uninstalled the gem from the default dir.
> `sudo gem uninstall fastlane-plugin-firebase_app_distribution`
> and then installed in user dir
> `gem install fastlane-plugin-firebase_app_distribution --user-install`
> 
> and now it works.

great answer,it work for me ,thanks!
